openapi: 3.0.0
info:
  title: Consortia integration API
  description: "Consortia integration API"
  version: 0.0.1
servers:
  - url: /consortia/
paths:
  /{consortiumId}/tenants:
    get:
      description: Get a list of tenants based on consortiumId
      operationId: getTenants
      parameters:
        - in: path
          name: consortiumId
          required: true
          description: Consortium Id
          schema:
            $ref: "#/components/schemas/UUID"
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
      responses:
        "200":
          description: 'Tenants successfully retrieved'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tenantCollection"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Save tenant
      operationId: saveTenant
      parameters:
        - in: path
          name: consortiumId
          required: true
          description: Consortium Id
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "201":
          description: 'Tenant successfully saved'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tenant"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tenant"
        required: true
  /user-tenants:
    get:
      description: User Tenant Associations
      summary: Get a list of user tenant associations
      operationId: getUserTenants
      parameters:
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
          description: The UUID of the user
        - in: query
          name: username
          schema:
            type: string
            description: The username of the user
        - in: query
          name: tenantId
          schema:
              type: string
          description: The ID of the tenant
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
      responses:
        "200":
          description: "User Tenant Associations successfully retrieved"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userTenantCollection"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /user-tenants/{associationId}:
    description: User Tenant Associations
    get:
      summary: Get a list of user tenant associations
      operationId: getUserTenantByAssociationId
      parameters:
        - $ref: "#/components/parameters/trait_path_association_id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userTenant"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    tenant:
      $ref: 'schemas/dto/tenant.json#/Tenant'
    tenantCollection:
      $ref: 'schemas/dto/tenantCollection.json#/TenantCollection'
    userTenant:
      $ref: 'schemas/dto/userTenant.json#/UserTenant'
    userTenantCollection:
      $ref: 'schemas/dto/userTenantCollection.json#/UserTenantCollection'
    error:
      $ref: 'schemas/error/error.json#/Error'
    errors:
      $ref: 'schemas/error/errors.json#/Errors'
    UUID:
      type: string
      format: uuid
  parameters:
    trait_path_association_id:
      in: path
      name: associationId
      schema:
        type: string
        format: uuid
      required: true
      description: UUID of the user to get and associated tenants.
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
