openapi: 3.0.0
info:
  title: Consortium integration API
  description: "Consortium integration API"
  version: 0.0.1
paths:
  /consortia:
    get:
      description: Get consortium collection
      operationId: getConsortiumCollection
      responses:
        "200":
          description: 'Consortia successfully retrieved'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/consortiumCollection"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    post:
      description: Save consortium
      operationId: saveConsortium
      responses:
        "201":
          description: 'Consortium successfully saved'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/consortium"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/consortium"
        required: true
  /consortia/{consortiumId}:
    get:
      description: Get consortium record based on consortiumId
      operationId: getConsortium
      parameters:
        - in: path
          name: consortiumId
          required: true
          description: Consortium Id
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: 'Consortium successfully retrieved'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/consortium"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    put:
      description: Update consortium name
      operationId: updateConsortium
      parameters:
        - in: path
          name: consortiumId
          required: true
          description: Consortium Id
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "204":
          description: 'Consortia name successfully updated'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/consortium"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the errors (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errors"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/consortium"
        required: true
components:
  schemas:
    consortiumCollection:
      $ref: 'schemas/dto/consortiumCollection.json#/ConsortiumCollection'
    consortium:
      $ref: 'schemas/dto/consortium.json#/Consortium'
    error:
      $ref: 'schemas/error/error.json#/Error'
    errors:
      $ref: 'schemas/error/errors.json#/Errors'
    UUID:
      type: string
      format: uuid
