openapi: 3.0.0
info:
  title: Tenant integration API
  description: "Tenant integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/
paths:

components:
  requestBodies:
    SyncPrimaryAffiliationsRequest:
      description: SyncPrimaryAffiliationsRequest object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/sync_primary_affiliation_body.yaml#/SyncPrimaryAffiliationBody"
  responses:
    Tenant:
      description: Returns a tenant object
      content:
        application/json:
          schema:
            $ref: "schemas/tenant.yaml#/Tenant"
    TenantCollection:
      description: Returns a tenant collection object
      content:
        application/json:
          schema:
            $ref: "schemas/tenant.yaml#/TenantCollection"
    NoContent:
      description: No content
    Conflict:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Errors"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
    tenantId:
      in: path
      name: tenantId
      schema:
        type: string
      required: true
      description: The ID of the tenant
