openapi: 3.0.0
info:
  title: Consortia integration API
  description: "Consortia integration API"
  version: 0.0.1
servers:
  - url: /consortia/{consortiumId}/
paths:
  /tenants:
    get:
      description: Get a list of tenants based on consortiumId
      operationId: getTenants
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/trait_pageable_offset"
        - $ref: "#/components/parameters/trait_pageable_limit"
      responses:
        "200":
          $ref: "#/components/responses/TenantCollection"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      description: Save tenant
      operationId: saveTenant
      parameters:
        - $ref: "#/components/parameters/consortiumId"
      requestBody:
        $ref: "#/components/requestBodies/TenantBody"
      responses:
        "201":
          $ref: "#/components/responses/Tenant"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /tenants/{tenantId}:
    put:
      description: Update tenant name
      operationId: updateTenant
      parameters:
        - $ref: "#/components/parameters/consortiumId"
        - $ref: "#/components/parameters/tenantId"
      requestBody:
        $ref: "#/components/requestBodies/TenantBody"
      responses:
        "204":
          $ref: "#/components/responses/Tenant"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  requestBodies:
    TenantBody:
      description: Tenant object
      required: true
      content:
        application/json:
          schema:
            $ref: "schemas/tenant.yaml#/Tenant"
  responses:
    Tenant:
      description: Returns a tenant object
      content:
        application/json:
          schema:
            $ref: "schemas/tenant.yaml#/Tenant"
    TenantCollection:
      description: Returns a tenant collection object
      content:
        application/json:
          schema:
            $ref: "schemas/tenant.yaml#/TenantCollection"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
    Unauthorized:
      description: Not authorized to perform requested action
      content:
        text/plain:
          example: unable to perform action -- unauthorized
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            $ref: 'schemas/common.yaml#/Errors'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "schemas/common.yaml#/Error"
  parameters:
    consortiumId:
      in: path
      name: consortiumId
      schema:
        $ref: "schemas/common.yaml#/uuid"
      required: true
      description: The ID of consortium
    tenantId:
      in: path
      name: tenantId
      schema:
        type: string
      required: true
      description: The ID of the tenant
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for
        the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
